### ISSUE TITLE
博客主题咨询

### ISSUE THREAD

**Issue by catwithtudou** [Everoot/Everoot#1]
hello everoot~今天看到了你的博客，无论是内容还是博客的主题都非常赞！！！！
所以想请教下博主的博客主题是如何实现的？我想实现一个类似的博客主题
如果是有现成的主题，可以问问下是哪个主题吗？如果是博主自己实现的，也希望帮忙解答下相应的技术栈呢，非常感谢！

**Comment by Everoot** [comment]
Hello呀, 非常感谢您的喜欢, 我使用的是这个mkdocs-material主题, 链接在这里:https://squidfunk.github.io/mkdocs-material/ .  关于配置, 我仅对主页部分稍微修改, 其他部分基本上使用的是默认配置. 我刚公开了我的Blog仓库, 希望对您有帮助.

**Comment by Everoot** [comment]
> hello everoot~今天看到了你的博客，无论是内容还是博客的主题都非常赞！！！！ 所以想请教下博主的博客主题是如何实现的？我想实现一个类似的博客主题 如果是有现成的主题，可以问问下是哪个主题吗？如果是博主自己实现的，也希望帮忙解答下相应的技术栈呢，非常感谢！

Hello呀, 非常感谢您的喜欢. 我使用的是mkdocs-material主题, 链接在这里https://squidfunk.github.io/mkdocs-material/. 关于配置部分我基本上就对主页进行了更改, 其他基本上是主题默认的. 我刚公开了Blog的仓库, 希望对您有帮助.

**Comment by catwithtudou** [comment]
非常非常感谢！一直想寻找这种类似文档知识库构建的主题，终于找到了一个理想的！
我也会持续follow大佬哈哈哈哈，向博主学习勒！
